.PHONY: help install dev test lint format check db-up db-down migrate revision contracts verify clean

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | awk 'BEGIN {FS=":.*?## "} {printf "  %-15s %s\n", $$1, $$2}'

install: ## Install Python dependencies (uv)
	uv sync --extra dev

dev: ## Run the API locally with hot reload (Postgres must be up)
	uv run uvicorn src.api.main:app --reload --host 0.0.0.0 --port 8000

test: ## Run pytest
	uv run pytest tests/ -v

lint: ## Lint + format-check + type-check
	uv run ruff check src/ tests/ scripts/
	uv run ruff format --check src/ tests/ scripts/
	uv run mypy src/

format: ## Auto-format and apply ruff fixes
	uv run ruff format src/ tests/ scripts/
	uv run ruff check --fix src/ tests/ scripts/

check: lint test verify ## Full local CI gate

db-up: ## Start Postgres in Docker
	docker compose up -d postgres

db-down: ## Stop and remove Postgres container
	docker compose down

migrate: ## Apply Alembic migrations to head
	uv run alembic upgrade head

revision: ## Create a new autogenerated Alembic revision (msg="...")
	uv run alembic revision --autogenerate -m "$(msg)"

contracts: ## Regenerate docs/CONTRACTS.md from Pydantic models
	uv run python scripts/generate_contracts_md.py > docs/CONTRACTS.md

verify: ## Run static invariant checks
	uv run python scripts/verify_invariants.py

clean: ## Remove caches and build artifacts
	rm -rf .pytest_cache .mypy_cache .ruff_cache htmlcov .coverage
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
